# Generated by Django 3.2.20 on 2023-07-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome_autor',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
